name: Update all changed member files

on:
  schedule:
    - cron: "25 16 * * 1"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Fetch main branch
        run: git fetch origin main:main
      - name: Install npm packages
        run: npm install
      - name: Update all changed member files
        run: bash ./bin/update-all-members
      - name: Commit member changes, if any
        run: bash ./bin/commit-member-changes
